project_id = "dsyhvjwxqbixeifkofgl"

[functions.process-payment]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.get-youtube-info]
verify_jwt = false

[functions.bkash-payment]
verify_jwt = false

[functions.bkash-callback]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
